#!/usr/bin/env python

# this script is a wrapper for execution in scriptlauncher

from pathlib2 import Path
import os
import sys
import subprocess

os.chdir(str(Path(sys.argv[1]).absolute().parent))
subprocess.call(sys.argv[2:])



