# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TRAVIS: 'true' # Skip tests requiring data
    strategy:
      matrix:
        python-version:
          - '3.10'
    name: Python ${{ matrix.python-version }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt install gcc libffi-dev libssl-dev nodejs npm libyaml-dev libxslt1-dev
          sudo apt install rustc cargo # needed for pip cryptography in some python versions without egg
          sudo apt install libegl1 libfuse2 # minizinc dependencies not in the appimage
      - name: Minizinc installation
        run: |
          wget -q https://github.com/MiniZinc/MiniZincIDE/releases/download/2.7.4/MiniZincIDE-2.7.4-x86_64.AppImage
          mv MiniZincIDE-2.7.4-x86_64.AppImage /usr/local/bin/minizinc
          chmod +x /usr/local/bin/minizinc
          minizinc --version
          minizinc --help

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install "setuptools_rust" # requirements for cryptography
          #pip install "cachetools<5.0" # requirement from google-auth
          #pip install "async-timeout<4.0" # requirement from aiohttp
          #pip install "aiohttp<3.8"
          pip install https://files.pythonhosted.org/packages/3e/5c/2867e46f03d2fcc3d014a02eeb11ec55f3f8d9eddddcc5578ae8457f84f8/ERPpeek-1.7.1-py2.py3-none-any.whl
          pip install -e .
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            coveralls
      - name: Unit tests
        run: |
          pytest --cov tomatic
      - name: B2B tests
        run: |
          touch holidays.conf
          back2back back2back.yaml
      - uses: actions/upload-artifact@master
        if: failure() && hashFiles('b2bdata/*result*')
        with:
          # TODO: use GITHUB_REF_NAME GITHUB_SHA
          name: b2b-results
          path: |
            b2bdata/*result*

      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
          flag-name: Unit tests

      - name: Google Chat Notificationa
        uses: SimonScholz/google-chat-action@main
        if: failure()
        # this allows the build to succeed even when the notification fails
        # e.g. due to dependabot push, which may not have the secret
        continue-on-error: true
        with:
          # https://docs.github.com/en/webhooks/webhook-events-and-payloads
          webhookUrl: ${{ secrets.WEBHOOK_ALERTES_WEBAPPS }}
          jobStatus: ${{ job.status }}
          imageUrl: ${{ format('https://github.com/{0}.png', github.event.head_commit.author.username) }}
          imageAltText: ${{ github.event.head_commit.author.name }}
          subtitle: ${{ github.event.head_commit.message }}
          title: "${{ format('{0} -- [{1}]', github.event.repository.name, github.event.ref) }}"

  coveralls_finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
